const all_subtypes = [
  "House",
  "Guest house",
  "Farmhouse",
  "Penthouse",
  "Apartment",
  "Hotel suite",
  "Room",
  "Upper portion",
  "Lower portion",
  "Basement",
  "Annexe",
  "Hostel",
  "Office",
  "Shop",
  "Building",
  "Plaza",
  "Warehouse",
  "Factory",
  "Theatre",
  "Gym",
  "Food court",
  "Hall",
  "Residential plot",
  "Commercial plot",
  "Industrial land",
  "Agricultural land",
  "Plot file",
  "Farmhouse plot",
  "Other",
];

const residential_subtypes = [
  "House",
  "Guest house",
  "Farmhouse",
  "Penthouse",
  "Apartment",
  "Hotel suite",
  "Room",
  "Upper portion",
  "Lower portion",
  "Basement",
  "Annexe",
  "Hostel",
  "Other",
];

const commercial_subtypes = [
  "Office",
  "Shop",
  "Building",
  "Plaza",
  "Warehouse",
  "Factory",
  "Theatre",
  "Gym",
  "Food court",
  "Hall",
  "Other",
];

const plot_subtypes = [
  "Residential plot",
  "Commercial plot",
  "Industrial land",
  "Agricultural land",
  "Plot file",
  "Farmhouse plot",
  "Other",
];

const unit_subtypes = [
  "Square Feet",
  "Square Yards",
  "Square Meters",
  "Marla",
  "Kanal",
];

const landmarks = [
  "School",
  "University",
  "Hospital",
  "Restaurant",
  "Grocery store",
  "Cinema",
  "Park",
  "Mosque",
];
const amenities = [
  "Amusement park",
  "Aquarium",
  "ATM access",
  "Backup power",
  "Barbeque area",
  "Broadband access",
  "Cafe area",
  "Capsule lifts",
  "CCTV security",
  "Central air conditioning",
  "Central heating",
  "Chauffeur service",
  "Conference rooms",
  "Elevator access",
  "Escalator access",
  "Gaming center",
  "Garbage disposal",
  "Gated security",
  "Gym",
  "Health club",
  "Indoor pools",
  "Infinity edge pool",
  "Jogging track",
  "Laundry facilities",
  "Library",
  "Lush gardens",
  "Luxury hotel suites",
  "Maintenance staff",
  "Media rooms",
  "Meeting areas",
  "Mosque",
  "Nearby hospitals",
  "Nearby mosque",
  "Nearby restaurants",
  "Nearby schools",
  "Office spaces",
  "Penthouses",
  "Play area",
  "Public park",
  "Public parking",
  "Reading room",
  "Recreational center",
  "Retail shops",
  "Road accessibility",
  "Rooftop restaurant",
  "Security staff",
  "Shopping center",
  "Spa room",
  "Sports center",
  "Theater",
  "Underground parking",
  "Valet service",
  "Walking track",
  "Warehouse facilities",
  "Water park",
];

export {
  all_subtypes,
  residential_subtypes,
  commercial_subtypes,
  plot_subtypes,
  unit_subtypes,
  landmarks,
  amenities,
};
